### PR TITLE
fix: do not walk into arrays when removing nulls

### LINKED ISSUE #713: Could not find schema arg with name: 0 "nexus-prisma": "^0.15.0-next.6",
In the latest version this query:
```
query getConversations($userId: String){
    conversations {
        conversations{
            id,
            profiles(where: {NOT: [{profile: {id: {equals: $userId}}}]}) {
                profile {
                    id,
                    profileName
                    images(where: {main: {equals: true}}){
                        path
                    }
                }
            }
            messages {
                id,
            }
        }
        count
    }
}
```

results in this error:

```

      "message": "Could not find schema arg with name: 0",
      "locations": [
        {
          "line": 5,
          "column": 7
        }
      ],
      "path": [
        "conversations",
        "conversations",
        0,
        "profiles"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Could not find schema arg with name: 0",
            "    at transformNullsToUndefined (/c/Users/bjoer/Documents/Projects/necom/node_modules/nexus-prisma/src/null.ts:24:13)",
            "    at transformNullsToUndefined (/c/Users/bjoer/Documents/Projects/necom/node_modules/nexus-prisma/src/null.ts:34:26)",
            "    at Object.transformNullsToUndefined (/c/Users/bjoer/Documents/Projects/necom/node_modules/nexus-prisma/src/null.ts:34:26)",
            "    at originalResolve (/c/Users/bjoer/Documents/Projects/necom/node_modules/nexus-prisma/src/builder.ts:498:24)",
            "    at /c/Users/bjoer/Documents/Projects/necom/node_modules/graphql-middleware/src/applicator.ts:34:9",
            "    at middleware (/c/Users/bjoer/Documents/Projects/necom/node_modules/graphql-shield/src/generator.ts:70:16)",
            "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
          ]
        }
      }
    }
  ],
  "data": {
    "conversations": {
      "conversations": null,
      "count": 3
    }
  }
}
```

I use nexusPrismaPlugin with 
```
            experimentalCRUD: true,
            paginationStrategy: 'prisma',
```
The nexus object is:
```
export const ConversationI = interfaceType({
    name: 'ConversationI',
    definition: (t) => {
        t.model('Conversation').id();
        t.model('Conversation').profiles({ filtering: true });
        /*
        t.field('messages', {
            nullable: true,
            list: [true],
            type: 'Message',
            args: {
                where: 'MessageWhereInput',
                orderBy: 'MessageOrderByInput',
                cursor: 'MessageWhereUniqueInput',
                take: 'Int',
                skip: 'Int',
            },
        });
        */
        t.model('Conversation').messages({
            filtering: true,
            ordering: true,
            pagination: true,
        });
        t.resolveType(() => {
            return 'Conversation';
        });
    },
});

```
The removed lines are working with version "^0.14.0"

### LINKED ISSUE #723: Could not find input type name: String
Hello.
I'm just trying to create a post using the mutation generate by the "t.crud", and i'm getting this error when trying to set a list of strings in argument:
"Could not find input type name: String"

This is the mutation:
```graphql
mutation {
  createPost(
    data: {
      title: "hello mundo"
      subtitle: "testing"
      edition: ""
      videoUrl: ""
      type: NEWS
      description: "this is a test description"
      categories: { set: [] }
    }
  ) {
    id
    categories
    title
    subtitle
    edition
    cover
    description
    videoUrl
  }
}
```

And here's my prisma.schema:
```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}
enum Type {
  MAGAZINE
  NEWS
}
/// The post entity
model Post{
  ///Id of the post
  id String  @id @default(cuid())
  ///Post title
  title String
  ///Post description
  description String?
  ///Post subtitle
  subtitle String?
  ///Post edition number
  edition String?
  ///Post cover image
  cover String?
  ///Post videoUrl
  videoUrl String?
  //Post categories
  categories String[] 
  ///Post images
  images String[]
  ///Post files
  files String[]
  ///Type of the post that can be news or magazine
  type Type @default(NEWS)
  ///Attribute that contains the audience of the post
  audience String[]
  ///Attribute that contains the id of the users who liked 
  likedBy String[]
  ///Who has deleted the post
  deletedBy String?
  ///When the post was deleted
  deletedAt DateTime?
  createdBy String?
  ///When the post was created
  createdAt DateTime @default(now())
  active Boolean @default(true)
  ///When the post was last updated
  updatedAt DateTime @updatedAt
  ///Who was the last user that updated the post
  updatedBy String?
}
```
Right now i'm getting this output: 
```json
{
  "errors": [
    {
      "message": "Could not find input type name: String",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createPost"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Could not find input type name: String",
            "    at DmmfDocument.getInputTypeWithIndexedFields (/home/mihazs/Dev/backend-cms-service/node_modules/nexus-prisma/src/dmmf/DmmfDocument.ts:53:13)",
            "    at transformNullsToUndefined (/home/mihazs/Dev/backend-cms-service/node_modules/nexus-prisma/src/null.ts:32:37)",
            "    at transformNullsToUndefined (/home/mihazs/Dev/backend-cms-service/node_modules/nexus-prisma/src/null.ts:34:26)",
            "    at Object.transformNullsToUndefined (/home/mihazs/Dev/backend-cms-service/node_modules/nexus-prisma/src/null.ts:34:26)",
            "    at originalResolve (/home/mihazs/Dev/backend-cms-service/node_modules/nexus-prisma/src/builder.ts:323:24)",
            "    at resolve (/home/mihazs/Dev/backend-cms-service/node_modules/nexus-prisma/src/builder.ts:349:21)",
            "    at /home/mihazs/Dev/backend-cms-service/node_modules/@nexus/schema/src/plugins/nullabilityGuardPlugin.ts:103:13",
            "    at lastResolver (/home/mihazs/Dev/backend-cms-service/node_modules/@nexus/schema/src/plugin.ts:176:14)",
            "    at /home/mihazs/Dev/backend-cms-service/node_modules/graphql-middleware/src/applicator.ts:34:9",
            "    at middleware (/home/mihazs/Dev/backend-cms-service/node_modules/graphql-shield/src/generator.ts:70:22)"
          ]
        }
      }
    }
  ],
```

And my implementation uses the createpost generate by the crud feature:
```
import { mutationField } from "@nexus/schema";
import { IPostCreateResolverFields } from "../index";
export const createPost = mutationField((t) => {
  t.crud.createOnePost({
    alias: "createPost",
    computedInputs: {
      createdBy: ({ ctx }: IPostCreateResolverFields) => ctx.user?.userId,
      createdAt: () => new Date(Date.now()).toISOString(),
      updatedAt: () => new Date(Date.now()).toISOString(),
      updatedBy: ({ ctx }: IPostCreateResolverFields) => ctx.user?.userId,
      deletedBy: () => null,
      deletedAt: () => null,
      likedBy: () => ({
        set: [],
      }),
      cover: () => null,
      images: () => ({
        set: [],
      }),
      files: () => ({
        set: [],
      }),
    },
  });
});
```
I've tried to remove the computed inputs, and the computed inputs that doesn't have a list, but no success.

I think that can be a bug.
Thanks.

### PR DESCRIPTION
**Pull request by Weakky**
Fixes https://github.com/graphql-nexus/nexus/issues/1074
Fixes #713

Note: There's no need to convert values in arrays as they are never nullable anyway.

### CODE REVIEW

File: src/schema/null.ts [hunk 1]
```diff
@@ -38,6 +39,6 @@ export function transformNullsToUndefined(
   return graphqlArgs
 }
 
-function isObject(obj: any): boolean {
-  return obj && typeof obj === 'object'
+function isObject(arg: any): arg is Record<string, any> {
```
Comment (jasonkuhrt) [inline src/schema/null.ts]: Let's just bring lodash into this and use its `isObject`. This here still doesn't account for `null` for example. And I don't feel like having to remember why that's ok this time.

Don't mind the extra package size at all. Once we tree shake instead of module shake, we'll save most cost anyways. But 500kb pales in comparison to the weight of other deps here and product time/user disruption in getting these details right.

Comment (Weakky) [reply src/schema/null.ts]: > This here still doesn't account for null for example

It does though. First condition is `arg &&`. Not sure there's a reason to bring it now ?

**Review by jasonkuhrt — APPROVED** [review]
🙌 

Let's see how it goes
